### ISSUE TITLE
Latin extended special characters

### ISSUE THREAD

**Issue by ozolnieks** [creativetimofficial/material-kit-pro#12]
�'�'�'�'�'�  I have got something like this, when I try to insert "āčēšī" characters.

**Comment by alexandru-paduraru** [comment]
@ozolnieks thank you for using our product and sorry for the late response. We added the chars that you tested and it si working fine:

<img width="1144" alt="screen shot 2017-04-22 at 14 01 38" src="https://cloud.githubusercontent.com/assets/2517758/25303855/4895d29e-2764-11e7-8d1d-dbc62b99b8e1.png">

Can you please give us more details about the issue? What browser and OS you have and what device?

In the meantime please make sure you include this:

in the 
```html
<head> 
     // here
    <meta charset="utf-8" />
.... 
</head> 
```
on your page.

Best,
Alex
