### ISSUE TITLE
iPad fixed issue with navbar-burger

### ISSUE THREAD

**Issue by dragosct10** [creativetimofficial/material-kit-pro#16]
Hi! For fixing the issue with navbar-burger take the uploaded file and just go to `assets/sass/material-kit/_responsive.scss` and replace the old file with the new one. Compile you're scss with [Koala](koala-app.com). Please be sure that you're output path is `assets/css/material-kit.css`. Hope that will help you! 

[_responsive.scss.zip](https://github.com/creativetimofficial/material-kit-pro/files/983740/_responsive.scss.zip)

Regards,
Dragos

**Comment by mkarnicki** [comment]
Hi, what is the "Ipad issue with navbar-burger"? I don't have an ipad, but would like to know if my site doesn't work on one :). Thanks!

**Comment by alexandru-paduraru** [comment]
@mkarnicki there was an issue which didn't show the navbar burger on some iPads depending on their screen size. That was fixed just by replacing the file that my colleague added.

**Comment by ConfusedVorlon** [comment]
@mkarnicki you can test in chrome. Just use the responsive inspector view and set the width to 768 (iPad portrait). You'll probably see that your normal menu disappears, and the hamburger isn't visible yet (it shows at 767)

**Comment by mkarnicki** [comment]
Thank you @ConfusedVorlon , appreciate it. My site was indeed affected!

**Comment by alexandru-paduraru** [comment]
@mkarnicki  and @ConfusedVorlon this was fixed in the latest v1.2.0. You can replace the material-kit.css and material-kit.js from the new archive and everything will work fine.

**Comment by ConfusedVorlon** [comment]
I have an observation here.

with regard to the hamburger and other responsive utilities

In bootstrap - 768 is treated as the non-mobile size
767 or lower is mobile 

this means that an iPad is non-mobile for portrait and landscape

in materialkit, 768 is considered mobile
this means that

1) an iPad can be both mobile and non-mobile (depending on orientation)
2) there are odd inconsistencies with other bootstrap breakpoints

**Comment by ConfusedVorlon** [comment]
thinking about it - this is really a separate issue. Please ignore it here and I'll start a new item.
