### ISSUE TITLE
Dropdown not reflected in collapsed navbar

### ISSUE THREAD

**Issue by RedDuckss** [creativetimofficial/material-kit-pro#22]
Dropdowns in the navbar work on desktops but do not function when collapsed, on mobile:
![bug](http://i.imgur.com/h4zlygg.gif)

**Comment by alexandru-paduraru** [comment]
@RedDuckss thank you for pointing out. Can you please make sure you are using the latest v1.1.1 version? For example in our presentation: http://demos.creative-tim.com/material-kit-pro/presentation.html everything is working fine if we are doing the same steps as you.

Best,
Alex

**Comment by RedDuckss** [comment]
Yes, I am using the latest version 1.1.1

**Comment by alexandru-paduraru** [comment]
@RedDuckss that is a very weird behavior, can you please make sure you use the navbar and the toggle exactly how we used in our examples? On the archive everything is working fine, please check this video: https://vimeo.com/220435505

Make sure you don't have the data-target id on your toggle button.

Best,
Alex

**Comment by RedDuckss** [comment]
The issue seems to have stemmed from some cached css preventing me from interacting with the dropdown while in the collapsed menu, not an issue with this lib. Clearing my cache fixed this issue, sorry for the trouble. Issue resolved.
