### ISSUE TITLE
Navbar issue with iPad in portrait mode

### ISSUE THREAD

**Issue by yusukeoshiro** [creativetimofficial/material-kit-pro#23]
Hi, 
I bought the product last week and I found a bug.
When you look at the navbar from an iPad in portrait mode, the navbar nor the burger button shows.
Is there a fix to this?

### iPad in horizontal
![screen shot 2017-06-04 at 23 22 35](https://cloud.githubusercontent.com/assets/11641437/26762415/eeb315c6-497c-11e7-806f-b91f28bdd027.png)

### iPad in portrait
![screen shot 2017-06-04 at 23 22 13](https://cloud.githubusercontent.com/assets/11641437/26762417/f0e66910-497c-11e7-9914-686a8d495ec8.png)

**Comment by alexandru-paduraru** [comment]
@yusukeoshiro thank you for using our product. Please check the fix that we prepared here: https://github.com/creativetimofficial/material-kit-pro/issues/16 

Best,
Alex

**Comment by yusukeoshiro** [comment]
Thanks that did it
