### ISSUE TITLE
Perspective Cards v1.1 Shadows broken on firefox

### ISSUE THREAD

**Issue by Jorden-** [creativetimofficial/material-kit-pro#30]
Perspective Cards v1.1 Shadows looks broken on firefox 54.0.1 

![image](https://user-images.githubusercontent.com/9530784/28436591-bce36980-6d97-11e7-99b1-43e6d8d2167d.png)

**Comment by alexandru-paduraru** [comment]
@Jorden- thank you for pointing that out. Can you please use the latest version of atvImg library: https://github.com/drewwilson/atvImg and let us know if that was working for you? 

Best,
Alex
