### ISSUE TITLE
Rotating Cards IE Text Flipped

### ISSUE THREAD

**Issue by davedags** [creativetimofficial/material-kit-pro#32]
in IE 11 on Windows 10, when you rotate a card all of the text/content from the front is shown and is flipped from right to left.  You do not see the contents of the back.  This issue is present in the material-kit-pro download as well as in my own site I was trying to use it on.

**Comment by alexandru-paduraru** [comment]
@davedags please check the solution from https://github.com/creativetimofficial/material-kit-pro/issues/33 and let us know your status :D

**Comment by weblackey** [comment]
I have the same issue.I tried every single step from post number #33 which actually leads to post #11

- I updated the material kit pro to version 1.1.1 
- I installed Koala and added the new cards scss and compiled a new material kit and copied the resulting CSS to assets
- I substituted the new material kit JS in assets

Absolutely no change in behavior.

Still with IE the back of the card is missing the content and instead only shows a flipped version of the front image

**Comment by weblackey** [comment]
Also Dynamic Shadows don't work in IE either, but both Rotating Cards and Dynamic Shadows work in Chrome... please fix this as it is holding up our web design with Material Kit Pro
