### ISSUE TITLE
Rotating Cards - iOS Browsers (Safari, Chrome) - Back of card is blank

### ISSUE THREAD

**Issue by davedags** [creativetimofficial/material-kit-pro#33]
On latest iOS, iphone 7, in Safari and chrome mobile browsers, the rotating card's back content isn't visible.  When I rotate, the card flips, the content is shown for a split second, and then it disappears.

**Comment by alexandru-paduraru** [comment]
@davedags thank you for the information. We added a fix here: https://github.com/creativetimofficial/material-kit-pro/issues/11#issuecomment-315996021 and here https://github.com/creativetimofficial/material-kit-pro/issues/11#issuecomment-316679041. Please follow those steps and it should work fine. We will have an official update soon.

Best,
Alex

**Comment by weblackey** [comment]
For me it works in iOS but doesn't work in IE, even after following all these steps

**Comment by dragosct10** [comment]
Hi @davedags! We just came with an update on Material Kit PRO. Please download the latest version `1.2.0` and rotating cards will work fine.

Regards,
Dragos
