### ISSUE TITLE
Rotating card in V 1.1.1 with Windows 7 / IE: image flips but the buttons don't show

### ISSUE THREAD

**Issue by weblackey** [creativetimofficial/material-kit-pro#37]
When checking your MK V1.1.1 "ecommerce" page, the rotating card works as expected in iOS and shows the rotated image as well as the contents (such as buttons) that are on the back. But on Windows 7 with IE only the image is shown and the buttons and other content on the back of the card are missing . This is with your own kit and nothing added, removed or changed.

**Comment by weblackey** [comment]
2 more pieces of information to help you trace the problem:
1) Chrome and iOS both work ok.  So far just Internet Explorer doesn't work
2) The Dynamic shadows also don't work in Internet Explorer but work in Chrome
What's common between the Dynamic Shadows and Rotating Cards ?

**Comment by weblackey** [comment]
Confirmed that this issue is also reproducible on Internet Explorer with Windows 10, while the Edge browser on Windows 10 works ok. In summary the rotating cards seem to work properly in Edge, Chrome, Safari but not in Internet Explorer on Windows 7, 8.1, or 10

**Comment by alexandru-paduraru** [comment]
@weblackey we responded here: https://github.com/creativetimofficial/material-kit-pro/issues/38#issuecomment-327785013 with more details. We are looking to take a decision about this. Let's keep the conversation there so we don't miss anything important.

Best,
Alex

**Comment by weblackey** [comment]
Hi Alex. Thanks for your response in #38 and I also responded there too

It really seems that you are very close to a solution. The cards do rotate. And selecting back-background also seems to have an effect. It's just that the content on the back doesn't show. It's interesting that it seems all your other features work, just Dynamic Shadow and Rotating Cards seem to have a problem. Maybe something common among these features is the issue, such as the initialization or debounce. It is definitely worth taking another look. Or maybe you could put a line at the end of the Javascipt for rotating the cards so that it detects IE and refreshes or repaints the background content. I'm not a JavaScript developer so I can't do much debugging there but it seems that since the card actually rotates the tough part is done and you're close to real solution and it would be a shame to give up on this.
