### ISSUE TITLE
data-parallax=true caused background to disappear after scrolling to the bottom of the page and scrolling it back up in mac chrome Version 61.0.3163.79 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by creativ89** [creativetimofficial/material-kit-pro#39]
Error encountered in Mac chrome version 61.0.3163.79 (Official Build) (64-bit)
i had set the following header message. 
<div class="page-header header-filter header-small" data-parallax="true" style="background-image: url('assets/img/image.png');">

when is scroll to the bottom of the page and scroll back up, the image becomes a gray background.

please advise. 
<img width="1062" alt="screen shot 2017-09-09 at 9 56 23 pm" src="https://user-images.githubusercontent.com/7222244/30240798-c437278c-95a9-11e7-95e7-14a28a0b0e2d.png">

**Comment by ConfusedVorlon** [comment]
this happens on the material kit pro live site

http://demos.creative-tim.com/material-kit-pro/presentation.html?_ga=2.123027915.1506552557.1505979067-65791285.1502875343

and in my own site (I'm also using the pro theme)

**Comment by dragosct10** [comment]
Hi @creativ89! To fix this issue please go in your project in `assets/js/material-kit.js` and search inside of the javascript object `materialKitDemo` which is on line `303` the function `checkScrollForParallax` and replace entire function with the following function:

```js
 checkScrollForParallax: debounce(function(){

         oVal = ($(window).scrollTop() / 3);
         big_image.css({
             'transform':'translate3d(0,' + oVal +'px,0)',
             '-webkit-transform':'translate3d(0,' + oVal +'px,0)',
             '-ms-transform':'translate3d(0,' + oVal +'px,0)',
             '-o-transform':'translate3d(0,' + oVal +'px,0)'
         });

     }, 6),
```

After you do that everything I hope will work good!

Regards,
Dragos
