### ISSUE TITLE
How do I fix this?

### ISSUE THREAD

**Issue by rushter777** [creativetimofficial/material-kit-pro#46]
jquery.min.js:2 Uncaught TypeError: $(...).tagsinput is not a function
    at HTMLDocument.<anonymous> (material-kit.js:49)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)
(anonymous) @ material-kit.js:49
j @ jquery.min.js:2
k @ jquery.min.js:2

**Comment by dragosct10** [comment]
Hi, @rushter777! Thank you for using our product and sorry for the late response. To fix this error, please call in the html page at the bottom of the page the library tagsinput with this code: `<script src="assets/js/bootstrap-tagsinput.js"></script>`. 
Regards,
Dragos

**Comment by rushter777** [comment]
Thanks.

On Dec 4, 2017 7:33 PM, "dragosct" <notifications@github.com> wrote:

Hi, @rushter777 <https://github.com/rushter777>! Thank you for using our
product and sorry for the late response. To fix this error, please call in
the html page at the bottom of the page the library tagsinput with this
code: <script src="assets/js/bootstrap-tagsinput.js"></script>.
Regards,
Dragos

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/creativetimofficial/material-kit-pro/issues/46#issuecomment-348922782>,
or mute the thread
