### ISSUE TITLE
Nav Pills

### ISSUE THREAD

**Issue by karate-island** [creativetimofficial/material-kit-pro#47]
Hey, I'm trying to use the Nav Pills, but for the vertical (with icons) option - I'm only able to add three, because they all seem to have to be tied to a pre-set id, namely, #dashboard-2, #schedule-2, and #tasks-2. I tried just adding another class (on the HTML), e.g. "#details-2" but it didn't work.
Is it possible to make extra nav pill id's so that I can have more than 3 nav pills?

Thanks

**Comment by alexandru-paduraru** [comment]
@karate-island yes, you can have as many tabs as you want, just duplicate the `li >a` elements with their own unique ids and `hrfes` and also the `.tab-pane` divs. Please check the official examples from Bootstrap: https://getbootstrap.com/docs/3.3/javascript/#markup

Hope this helps.

Best,
Alex
