### ISSUE TITLE
navbar-primary navbar-fixed-top navbar-color-on-scroll on page refresh

### ISSUE THREAD

**Issue by JDesignEra** [creativetimofficial/material-kit-pro#51]
There seem to be some issues with `navbar-transparent navbar-color-on-scroll` on page refresh. If you refresh when the navbar has already turned into solid-colour / in the middle of the page, it will be transparent upon refresh. The issues seem to persist in both Chrome and FireFox browser. Though Internet Explorer seems to be fine.

Anyway, this issue happens only when I followed the profile-page.html template closely. I have tried the pricing.html and it seems to working fine though. Is there a quick-fix to this issue?

I am on **material-kit-pro 1.2.1** version anyways.

My navbar section only:
```HTML
<!-- navbar	-->
<nav class="navbar navbar-primary navbar-transparent navbar-fixed-top navbar-color-on-scroll" color-on-scroll="1">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse">
				<span class="sr-only">Toggle Navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="index.html"><img src="assets/img/base/logos/logo_x50_light.png" alt="Logo" /></a>
		</div>

		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li class="active">
					<a href="#profile">
						<i class="material-icons">face</i> Profile
					</a>
				</li>
				<li>
					<a href="#portfolio">
						<i class="material-icons">view_quilt</i> Portfolio
					</a>
				</li>
				<li>
					<a href="#services">
						<i class="material-icons">work</i> Services
					</a>
				</li>
				<li>
					<a href="#skills-tools">
						<i class="material-icons">build</i> Skills & Tools
					</a>
				</li>
			</ul>
		</div>
	</div>
</nav>
<!-- /.navbar -->
```

After some further testing, it might be an issue with using `<img>` as a navbar-brand, and `<script  type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR KEY HERE"></script>` seems to be needed too for the navbar to work as intended, which is weird...

**There seems to be an issue when using #anchorTag for nav url it too. When url is `https://website.com/#anchorTag`, upon refresh the nav would not be solid colour if you are in the middle of the page.**

**Comment by alexandru-paduraru** [comment]
@JDesignEra thank you for pointing out. Please check the solution for the navbar here: https://github.com/creativetimofficial/material-kit-pro/issues/43 

Best,
Alex
