### ISSUE TITLE
Manual Flipping cards issue

### ISSUE THREAD

**Issue by rushter777** [creativetimofficial/material-kit-pro#67]
The manual flipping cards only works on an Android phone display. On full screen Chrome if you have more than one card, they layer themselves on top of each other. In Safari, they are listed but the buttons, when using them, are layered on top of each on the bottom of the page. Not sure if this is a JS issue or CSS issue but I am pretty sure the CSS is ok.

**Comment by dragosct10** [comment]
Hi, @rushter777! Thank you for using our product. Please, can you show us an video example of what you said in the message? 

Regards, 
Dragos

**Comment by rushter777** [comment]
I can't make a video but you can check out the page here.

https://www.englishmenusavailable.com/mk/searchcards.php

**Comment by dragosct10** [comment]
Hi, @rushter777! I noticed that you don't have any container with rows and cols for that cards. Regards, Dragos

**Comment by rushter777** [comment]
Got it, thanks. I just copied the examples.

**Comment by rushter777** [comment]
You should not have closed - I added the row and columns css and it works in chrome but  safari is still incorrect.

**Comment by dragosct10** [comment]
Hi, @rushter777! I test on safari and I don't see what are the problems there. Please see this [video](https://www.dropbox.com/s/i3tna3u3ynyo6ra/mk-pro-safari-flip-card.mov?dl=0). 

Regards,
Dragos

**Comment by rushter777** [comment]
Fiverr
    
    
            
      {
          "@context": "http://schema.org",
          "@type": "EmailMessage",
          "action": {
            "@type": "ViewAction",
            "url": "https://www.fiverr.com/s2/18b44fc606",
            "name": "Browse Services on Fiverr"
          },
          "description": "Browse Services on Fiverr"
      }
    

        
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    

                                        
    

    
        Scott is tired of keeping Fiverr a secret.
    

    
        Discover the easiest way to hire online freelancers and get 20% off your first order. From marketing to tech, complete all your projects on Fiverr. On budget. On time.
    

    
        Sounds too good to be true? See for yourself!
    



                                        
                                            
                                                
                                                    
                                                        
                                                            Browse Services On Fiverr
                                                        
                                                    
                                                
                                                
                                                    
                                                        

		
			
			
			The Fiverr Team
		
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
                
                    
                        
                            
                                

                                    © Fiverr International Limited 2010-2018, Fiverr Inc. | 401 Broadway, Suite 1600 New York NY, 10013 USA.
                                    Your personal information will not be stored or used for any marketing purposes.
                                
                            
                         
                    
                
            
        
            

    
If you would like to unsubscribe and stop receiving these emails click here.
