### ISSUE TITLE
Require tabs

### ISSUE THREAD

**Issue by pngmark** [creativetimofficial/material-kit-pro#7]
For the Pro version, are there tabs?

**Comment by alexandru-paduraru** [comment]
@pngmark thank you for your interest in our product. Please check the components page: http://demos.creative-tim.com/material-kit-pro/index.html#nav-tabs and you will see there are 6 types of tabs and pills with and without icons with different designs and inside/outside cards. Hope that will help you.

Please let us know if we can help you with anything else.

Best,
Alex
