### ISSUE TITLE
Failed to instantiate component 

### ISSUE THREAD

**Issue by qutub-bharmal** [creativetimofficial/material-kit-pro#77]
Hello,

I have using material kit pro in WordPress, but when I am logged in with admin and try to visit the website, it gives me following error.

```
Failed to instantiate component: $('input:not([type=hidden]):not([type=checkbox]):not([type=radio]):not([type=file]):not([type=button]):not([type=submit]):not([type=reset])')[bmdText]([object Object]) Error: e element: <input class="adminbar-input" name="s" id="adminbar-search" type="text" value="" maxlength="150"> requires class: form-control
    at Function.error (jquery.js?ver=1.12.4:2)
    at e.n._rejectWithoutRequiredClasses (material-kit.min.js?ver=2.0.2:5)
    at e [as constructor] (material-kit.min.js?ver=1.0.0:5)
    at e [as constructor] (material-kit.min.js?ver=1.0.0:5)
    at new e (material-kit.min.js?ver=2.0.2:5)
    at HTMLInputElement.<anonymous> (material-kit.min.js?ver=2.0.2:5)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.e._jQueryInterface [as bmdText] (material-kit.min.js?ver=2.0.2:5)
    at r (material-kit.min.js?ver=2.0.2:5) 
Selected elements:  [input#adminbar-search.adminbar-input, selector: "input:not([type=hidden]):not([type=checkbox]):not(…ype=button]):not([type=submit]):not([type=reset])", prevObject: n.fn.init(1), context: document]
```

Can you please check this.

**Comment by dragosct10** [comment]
Hi, @qutub-bharmal! The error is because on all of your inputs you must have the class `.form-control`. Regards, Dragos

**Comment by qutub-bharmal** [comment]
we can't change WordPress default admin panel. it should work if only input have class form-control, but should not raise error if class does not exit in any input.

**Comment by qutub-bharmal** [comment]
Hello,

any updates on this ?

**Comment by dragosct10** [comment]
Hi, @qutub-bharmal! Sorry for the late response. We inspected this and the source of this error is from the [material bootstrap design](https://fezvrasta.github.io/bootstrap-material-design/) so this is not from our javascript code. 

Regards, 
Dragos

**Comment by qutub-bharmal** [comment]
Yes, But your product is using material bootstrap design js. so I think you should ask them to resolve that error or there should be a possibility to user your product without that js.

can you please help to resolve this issue fast now as it's already too late now.

**Comment by dragosct10** [comment]
Hi! Can you use laravel debug on the WordPress? I think this is the way to fix the problem. Please check this #52. Regards, Dragos

**Comment by qutub-bharmal** [comment]
I didn't get you by laravel debug on the WordPress, I simply created a WordPress theme and for design purpose I am using material kit js files and css files only. yes I have already disabled WP_DEBUG which is of WordPress. please let me know what can I do here?

**Comment by dragosct10** [comment]
Hi! Unfortunately, we don't work with Wordpress so we don't know the framework. I thought that the answer of our user will help you because he had the same issue with you. Please tell me how you inserted all the HTML in the WordPress? Regards, Dragos

**Comment by qutub-bharmal** [comment]
I have created a shortcodes with Unyson page builders. but I don't think it's issue with the HTML added.

It is the problem of the form fields available without "form-control" class. but these fields are added by WordPress at top admin bar. so normally we can't change code of the WordPress Admin bar.

But I think the solution is that, your JS should not be generate the error if any form field does not have a form-control class, but it should simple work with only those field which have form control class. it is okay if it will not work for other fields.

**Comment by dragosct10** [comment]
Hi! Yes, we also have this problem with the js but we added on all of our inputs the class `.form-control`. Now I understand why the error appears in your project because WordPress inject the inputs in the HTML. Is it really no other option to edit the Wordpress to not inject any more inputs in your HTML? Regards, Dragos

**Comment by qutub-bharmal** [comment]
I can't edit WordPress files, as the changes will be lost on WordPress update. I also creating a theme as a product so I can't ask users to edit WordPress file.

So it's not possible to edit WordPress core files.

**Comment by dragosct10** [comment]
Hi! I'm trying to talk with the author of material bootstrap design to see how to fix this issue and I will come back to you. Regards, Dragos

**Comment by qutub-bharmal** [comment]
Yes Please, Thanks for this.

Awaiting your reply.

**Comment by dragosct10** [comment]
Hi, @qutub-bharmal! Please take the uploaded file and put in your assets/js. This file will not generate for you anymore that error. Regards, Dragos 

[bootstrap-material-design.js.zip](https://github.com/creativetimofficial/material-kit-pro/files/1847369/bootstrap-material-design.js.zip)

**Comment by qutub-bharmal** [comment]
Yes, it's works fine.

Thanks.

**Comment by RobertBoes** [comment]
It seems like the issue is within material kit pro, I can't really reproduce the issue in [FezVrasta/bootstrap-material-design](https://github.com/FezVrasta/bootstrap-material-design). Here is my codepen: https://codepen.io/anon/pen/MVxWRQ this shows it works on multiple ways: input in html, add an input with jQuery and adding an input after the document is loaded.

Some sort of solution has been offered here, but this no longer works if the library is updated, so it's not a long term solution if you ask me.

@dragosct10 If the fix is within bootstrap-material-design, do you expect them to implement this (and you bundle it with the next minor release), or won't there be a "real" solution?

**Comment by dragosct10** [comment]
Hi, @RobertBoes! Thank you for using our product. If you will remove from our product the library from fezvrasta you will see that nothing from these issues will happen, so this is happening from his library and I also know that when an update of the library will be available the issues will appear. For the moment we hope that when fezvrasta will do an update to fix that issues or we must change again his library, but like I said we hope to fix this issues. Regards, Dragos

**Comment by tweichart** [comment]
is there some issues that's opened at the bootstrap-material-theme that corresponds to this problem?

**Comment by dragosct10** [comment]
Hi, @tweichart! Thank you for using our product. No, there are no issues like this opened there but, take that file that I uploaded above and will fix the problem. Regards, Dragos

**Comment by tweichart** [comment]
yep, just used it, worked like a charm. but without the issue, who will this ever be fixed in the original library? ^^

**Comment by oasis9** [comment]
The file is no longer available. Could someone please reupload it?
