### ISSUE TITLE
Mixins problem in scss files during gulp compiling

### ISSUE THREAD

**Issue by flamisz** [creativetimofficial/material-kit-pro#81]
I have a problem with the scss files. This wasn't a problem previously.

`Error: Mixins may not be defined within control directives or other mixins.`

I got the same error with webpack.

version: `material-kit-pro-html-v2.0.2`

```
[11:16:36] Using gulpfile ~/dev/material/gulpfile.js
[11:16:36] Starting 'compile:scss'...
Error in plugin 'sass'
Message:
    assets/scss/core/mixins/_utilities.scss
Error: Mixins may not be defined within control directives or other mixins.
        on line 53 of assets/scss/core/mixins/_utilities.scss
>>     @mixin badges-color($color){

   -----------^

[11:16:36] Finished 'compile:scss' after 243 ms
```

**Comment by dragosct10** [comment]
Hi, @flamisz! Please take the latest update of the product 2.0.3 and the scss will not generate errors anymore. Regards, Dragos

**Comment by flamisz** [comment]
Thanks, but my company bought it on getbootstrap.com and it is still on 2.0.2 there.
If I re-download I just get that version. Is there any way to upgrade it to 2.0.3?

![screen shot 2018-03-28 at 7 59 00 am](https://user-images.githubusercontent.com/6749509/37988652-f501a4ea-325d-11e8-8a0c-fbe21e516bd1.png)

**Comment by dragosct10** [comment]
Hi, @flamisz! Please make an account on our site and then you can give me the username and I will give you the new version. Regards, Dragos

**Comment by flamisz** [comment]
Hi @dragosct10,
username: webdeva9t
email: webdev@trendsideas.com

Thanks

**Comment by dragosct10** [comment]
Hi, @flamisz! We just added you the product to your account. Regards, Dragos

**Comment by flamisz** [comment]
Thanks.

**Comment by zDrakon** [comment]
I am having the same issue, downloaded the latest version from https://www.creative-tim.com/product/material-kit 2.0.3 with bootstrap 4. 

Gulp watch is throwing the error of 

`[16:36:08] Using gulpfile ~/Desktop/material-kit-html-v2.0.2/BS4/gulpfile.js
[16:36:08] Starting 'watch'...
[16:36:08] Finished 'watch' after 252 ms
[16:36:12] Starting 'compile-scss'...
Error in plugin 'sass'
Message:
    assets/scss/core/mixins/_utilities.scss
Error: Mixins may not be defined within control directives or other mixins.
        on line 53 of assets/scss/core/mixins/_utilities.scss
>>     @mixin badges-color($color){
`

**Comment by dragosct10** [comment]
Hi, @zDrakon! Thank you for using our products. You compile the scss with the version 2.0.2. Regards, Dragos

**Comment by zDrakon** [comment]
@dragosct10 I just showed the error... I am using version 2.0.2.. It does not compile

**Comment by dragosct10** [comment]
Hi, @zDrakon! Sorry for my answer. I wanted to tell you that you must compile the scss with the version 2.0.3 of the product. Regards, Dragos

**Comment by zDrakon** [comment]
@dragosct10 Where is this 2.0.3? I do not see it in the latest official download link.

**Comment by dragosct10** [comment]
Hi! You bought the theme from getbootstrap, right? Regards, Dragos

**Comment by zDrakon** [comment]
No I downloaded it from creativetim the free version online. Its version 2.0.2 still but same error here.

**Comment by dragosct10** [comment]
Please, be more attention because you are on the material kit pro repo and it's confusing. We will made an update today for the Material Kit Free. Regards, Dragos
