### ISSUE TITLE
datetimepicker form bug

### ISSUE THREAD

**Issue by davidnpaul** [creativetimofficial/material-kit-pro#82]
The material-kit-pro datetimepicker doesn't work inside a form.

**Comment by dragosct10** [comment]
Hi, @davidnpaul! Thank you for using our product. Please take the uploaded js file and go to assets/js and replace this file. Regards, Dragos 

[bootstrap-material-design.js.zip](https://github.com/creativetimofficial/material-kit-pro/files/1867462/bootstrap-material-design.js.zip)

**Comment by davidnpaul** [comment]
Thanks Dragos... that seems to have fixed the problem. Cheers... Paul.

**Comment by itasouza** [comment]
> Hi, @davidnpaul! Thank you for using our product. Please take the uploaded js file and go to assets/js and replace this file. Regards, Dragos
> 
> [bootstrap-material-design.js.zip](https://github.com/creativetimofficial/material-kit-pro/files/1867462/bootstrap-material-design.js.zip)

I could make the file available again, I have the pro version, I'm having the same problem.

**Comment by itasouza** [comment]
> Hi, @davidnpaul! Thank you for using our product. Please take the uploaded js file and go to assets/js and replace this file. Regards, Dragos
> 
> [bootstrap-material-design.js.zip](https://github.com/creativetimofficial/material-kit-pro/files/1867462/bootstrap-material-design.js.zip)

Getting the file downloaded, improved, plus the calendar arrows are not displayed

**Comment by rlblanco** [comment]
Hi, I'm having the same problem with my Pro version.

Could you make available the patch again please?
