### ISSUE TITLE
Unable to compile scss 

### ISSUE THREAD

**Issue by LambertStrategy** [creativetimofficial/material-kit-pro#84]
Following the steps in the documentation and other issues noted for 2.0.3 I can't change the colors on the product site. Help would be much appreciated. NPM is installed correctly and running in the folder.

**Comment by dragosct10** [comment]
Hi! Please what are the problems that you have, you have some errors what happens there? Regards, Dragos

**Comment by LambertStrategy** [comment]
Hi Dragos, happy to report that gulp-compile worked with my setup. I had to change the gulp file's json directory on line no. 30 ( gulp.src) I believe that was the problem.
